### ISSUE TITLE
Add VS Code Extension URL to "Website" on GitHub Right Column?

### ISSUE THREAD

**Issue by karlhorky** [JannisX11/batch-rename#1]
Hi @JannisX11 , thanks so much for open-sourcing this!!

Would you be open to adding the link to the extension in the right column, in the Website URL underneath the `About` description? You can add it by clicking on the gear on the top right.

https://marketplace.visualstudio.com/items?itemName=JannisX11.batch-rename-extension

I would do a pull request, but GitHub doesn't allow for suggesting changes to the Website of a project yet...

**Comment by JannisX11** [comment]
Yeah sure.

**Comment by karlhorky** [comment]
Thanks! Have a great weekend!
