### ISSUE TITLE
Idea: do the same for variables in editor

### ISSUE THREAD

**Issue by zardoy** [JannisX11/batch-rename#11]
HI! I personally found useful useful having a way to rename multiple symbols within editor, when you have a lot of variables declaraed in one place using some name pattern eg:

```ts
// want to rename a bunch of variables safely
const sendButtonEnabled = true;
const sendButtonColor = 'red';
const sendButtonBackgroundColor = 'green';

...
```

Workflow: using multiselect select all needed variables, rename them in the same way

You can look at [Multi Rename Extension](https://marketplace.visualstudio.com/items?itemName=zardoy.multi-rename)

**Comment by JannisX11** [comment]
Cool! But why did you open an issue here if you have already made this?

**Comment by zardoy** [comment]
I thought it might be worth also putting that logic in your awesome extension as well (just because this extension doesn't have name ilke batch-files-renames).
The first part of functionality to rename files and the second to rename symbols. Feel free to close this issue if you don't like the idea of having it here.

**Comment by JannisX11** [comment]
Yeah I think it would be out of scope.

**Comment by airtonix** [comment]
dissapointing @JannisX11: 

- rename with vscode
  - file is renamed
  - all symbol references to file are updated.
- rename with batch-rename
  - all files are renamed
  - now i have to go through my entire repo of fifty eleventy billion files looking for the old filename and rename it myself.


I'd say that Batch-Rename doesn't live up to the expectations of a user
