### ISSUE TITLE
Introduce an icon

### ISSUE THREAD

**Issue by isidorn** [JannisX11/batch-rename#6]
Hi VS Code PM here 👋 

We really like you extension and we decided to feature it on the main marketplace page https://marketplace.visualstudio.com/

To make this look better it would be great if you can use an icon?
If you do not have any icon maybe use Dall-E-2 to generate an icon?

Thanks
Isidor

**Comment by JannisX11** [comment]
I'll come up with something!

**Comment by isidorn** [comment]
Thanks! Looks good
![Screenshot 2022-11-09 at 19 29 58](https://user-images.githubusercontent.com/1926584/200912032-f05a1cea-68df-4e61-b938-6d895fd33e77.png)

**Comment by oxmed354** [comment]
noreply@github.com

**Comment by oxmed354** [comment]
noreply@github.com
